databases:
  - name: ttp23crud
    databaseName: ttp23crud
    user: ttp23crud_user

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: postgres://ttp23crud_user:XNxGl2HOV9hhQWHgBSIVQYe5SpDMKZEQ@dpg-cik22cp8g3nc2gf3ugpg-a/ttp23crud
     fromDatabase:
       name: ttp23crud
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50 